### ISSUE TITLE
PackageLoader exception

### ISSUE THREAD

**Issue by dariocast** [brignoni/py-five-minute-journal#8]
When I run the application, I get:
```
Traceback (most recent call last):
  File "/Users/dariocastellano/Projects/py-five-minute-journal/journal.py", line 37, in <module>
    main()
  File "/Users/dariocastellano/Projects/py-five-minute-journal/journal.py", line 16, in main
    storage = MarkdownStorageProvider(
  File "/Users/dariocastellano/Projects/py-five-minute-journal/providers/MarkdownStorageProvider.py", line 15, in __init__
    loader=PackageLoader('journal', dir),
  File "/Users/dariocastellano/Projects/py-five-minute-journal/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'journal' package was not installed in a way that PackageLoader understands.
```

It seems an error on package loader but they assure they fixed it. I report here but I don't know how to solve at the moment. If I come out with a fix I will PR it

**Comment by dariocast** [comment]
Ok the problem is when the OUTPUT_DIR is set outside the application source directory. Maybe this cpould be an improvement

**Comment by brignoni** [comment]
Thank you @dariocast for reporting this. I will take a look today.

**Comment by brignoni** [comment]
@dariocast This should be fixed. I tested on my machine. Let me know if it works for you. Thanks
